
(custom-set-variables
 '(TeX-default-mode (quote plain-tex-mode))
 '(bar-cursor 2)
 '(buffers-menu-submenus-for-groups-p t)
 '(buffers-tab-max-buffer-line-length 40)
 '(buffers-tab-max-size 16)
 '(buffers-tab-switch-to-buffer-function (quote switch-to-buffer))
 '(c-basic-offset 4)
 '(case-fold-search t)
 '(column-number-mode t)
 '(comment-fill-column 79)
 '(comment-line-start "c")
 '(cperl-continued-brace-offset -4)
 '(cperl-continued-statement-offset 4)
 '(cperl-electric-keywords nil)
 '(cperl-electric-parens nil)
 '(cperl-electric-parens-mark t)
 '(cperl-font-lock t)
 '(cperl-hairy nil)
 '(cperl-highlight-variables-indiscriminately nil)
 '(cperl-indent-level 4)
 '(cperl-invalid-face (quote underline))
 '(cperl-label-offset -4)
 '(cperl-pod-here-scan t)
 '(cperl-regexp-scan t)
 '(cperl-syntaxify-by-font-lock t)
 '(cperl-syntaxify-unwind t)
 '(cperl-use-syntax-table-text-property t)
 '(cperl-use-syntax-table-text-property-for-tags t)
 '(default-gutter-position (quote top))
 '(delete-key-deletes-forward t)
 '(display-time-24hr-format t)
 '(display-time-day-and-date nil)
 '(display-time-display-pad (quote transparent))
 '(display-time-display-time-background (quote transparent))
 '(display-time-display-time-foreground "white")
 '(display-time-echo-area nil)
 '(display-time-form-list (quote nil))
 '(display-time-interval 15)
 '(display-time-mail-balloon nil)
 '(display-time-show-icons-maybe t)
 '(ediff-use-toolbar-p t)
 '(enable-recursive-minibuffers t)
 '(fast-lock-mode nil nil (fast-lock))
 '(fast-lock-verbose nil)
 '(fill-column 79)
 '(find-file-compare-truenames t)
 '(focus-follows-mouse t)
 '(font-lock-mode t nil (font-lock))
 '(fortran-blink-matching-if t)
 '(fortran-check-all-num-for-matching-do t)
 '(frame-background-mode (quote dark))
 '(gnuserv-frame t)
 '(gnuserv-program (concat exec-directory "/gnuserv"))
 '(gutter-buffers-tab-visible-p t)
 '(indent-tabs-mode nil)
 '(init-face-from-resources t)
 '(lazy-shot-mode nil nil (lazy-shot))
 '(line-number-mode t)
 '(make-backup-files nil)
 '(modeline-click-swaps-buffers t)
 '(modeline-scrolling-method t)
 '(mouse-track-rectangle-p nil)
 '(mouse-yank-at-point nil)
 '(outline-glyphs-on-left t)
 '(overwrite-mode nil)
 '(paren-mode (quote sexp) nil (paren))
 '(pending-delete-mode t nil (pending-del))
 '(progress-feedback-use-echo-area t)
 '(py-smart-indentation nil)
 '(query-replace-highlight nil)
 '(recent-files-actions-on-top t)
 '(recent-files-add-menu-before "Buffers")
 '(recent-files-commands-submenu t)
 '(recent-files-dont-include (quote ("\\.shadow")))
 '(recent-files-menu-title "Bookmarks")
 '(recent-files-non-permanent-submenu nil)
 '(recent-files-number-of-entries 20)
 '(recent-files-permanent-first t)
 '(recent-files-use-full-names nil)
 '(selective-display nil)
 '(tab-width 4)
 '(toolbar-visible-p nil)
 '(truncate-lines t)
 '(truncate-partial-width-windows t)
 '(vc-mode-face nil)
 '(whitespace-install-submenu t))
(custom-set-faces
 '(default ((t (:foreground "white" :size "14pt" :family "Courier"))) t)
 '(about-link-face ((((class color) (background light)) (:foreground "#4080ff" :underline t))))
 '(border-glyph ((t (:foreground "#A04040"))) t)
 '(buffers-tab ((t (:foreground "gray95" :background "gray40"))) t)
 '(cperl-array-face ((((class color) (background dark)) (:foreground "pink2"))))
 '(cperl-hash-face ((((class color) (background dark)) (:foreground "pink2"))))
 '(cperl-here-face ((t (:foreground "#709088"))))
 '(cperl-nonoverridable-face ((((class color) (background dark)) (:foreground "#60B8D0"))))
 '(cperl-pod-face ((((class color) (background dark)) (:foreground "#709088"))))
 '(cperl-pod-head-face ((((class color)) (:bold t :foreground "#A0B090"))))
 '(custom-comment-tag-face ((((class color) (background light)) (:foreground "#60A0F0"))))
 '(custom-face-tag-face ((t nil)))
 '(custom-group-tag-face ((((class color) (background light)) (:foreground "#20D0FF"))))
 '(custom-group-tag-face-1 ((((class color) (background light)) (:foreground "#FFD020"))))
 '(custom-saved-face ((t nil)))
 '(custom-state-face ((((class color) (background light)) (:foreground "#A0E0B0"))))
 '(custom-variable-button-face ((t (:bold t))))
 '(custom-variable-tag-face ((((class color) (background light)) (:foreground "#20D0FF"))))
 '(ediff-even-diff-Ancestor ((((class color)) (:foreground "White" :background "Grey40"))))
 '(ediff-even-diff-B ((((class color)) (:foreground "White" :background "Grey40"))))
 '(ediff-odd-diff-A ((((class color)) (:foreground "White" :background "Grey40"))))
 '(ediff-odd-diff-C ((((class color)) (:foreground "White" :background "Grey40"))))
 '(font-latex-bold-face ((((class color) (background dark)) (:foreground "white" :bold t))))
 '(font-latex-italic-face ((((class color) (background dark)) (:foreground "white" :italic t))))
 '(font-latex-math-face ((((class color) (background dark)) (:foreground "BlanchedAlmond"))))
 '(font-latex-warning-face ((((class color) (background dark)) (:foreground "#6080FF"))))
 '(font-lock-builtin-face ((((class color) (background light)) (:foreground "#20D0D0"))))
 '(font-lock-comment-face ((t (:foreground "#90a0a0"))))
 '(font-lock-constant-face ((((class color) (background dark)) (:foreground "RosyBrown3"))))
 '(font-lock-doc-string-face ((t (:foreground "BlanchedAlmond"))))
 '(font-lock-emphasized-face ((t (:bold t :background "#606000"))) t)
 '(font-lock-function-name-face ((t (:foreground "#F0F0FF"))))
 '(font-lock-keyword-face ((t (:foreground "DeepSkyBlue4"))))
 '(font-lock-other-emphasized-face ((t (:bold t :background "#606000"))) t)
 '(font-lock-other-type-face ((t (:foreground "#FFFFFF"))) t)
 '(font-lock-preprocessor-face ((t (:foreground "SteelBlue2"))))
 '(font-lock-reference-face ((t (:foreground "RosyBrown3"))))
 '(font-lock-string-face ((t (:foreground "#f0d0a0"))))
 '(font-lock-type-face ((t (:foreground "SteelBlue2"))))
 '(font-lock-variable-name-face ((t (:foreground "PaleGreen3"))))
 '(highlight ((t (:foreground "white" :background "orchid3"))) t)
 '(html-helper-link-face ((t (:foreground "steelblue"))))
 '(html-helper-significant-tag-face ((t (:foreground "#30E0C0"))))
 '(isearch ((t (:foreground "white" :background "orchid3"))) t)
 '(isearch-secondary ((t (:foreground "white" :background "#8B3769"))) t)
 '(list-mode-item-selected ((t (:background "gray68"))) t)
 '(modeline ((t (:foreground "gray70" :background "gray25"))) t)
 '(modeline-buffer-id ((t (:foreground "gray70" :background "gray25"))) t)
 '(modeline-mousable ((t (:foreground "gray70" :background "gray25"))) t)
 '(modeline-mousable-minor-mode ((t (:foreground "gray80" :background "gray25"))) t)
 '(paren-match ((t (:background "#103030"))) t)
 '(paren-mismatch ((t (:background "#401020"))) t)
 '(primary-selection ((t (:background "gray25"))) t)
 '(secondary-selection ((t (:background "turquoise"))) t)
 '(text-cursor ((t (:foreground "Black" :background "Tomato"))) t)
 '(vertical-divider ((t (:foreground "black" :background "Gray25"))) t)
 '(vvb-face ((t (:foreground "white" :background "#A04040"))) t)
 '(whitespace-blank-face ((t (:background "#406060"))))
 '(whitespace-tab-face ((t (:underline t :background "#404060"))))
 '(whitespace-visual-blank-face ((t (:background "#106080"))))
 '(whitespace-visual-tab-face ((t (:background "#208080" :underline t))))
 '(widget-button-pressed-face ((((class color)) (:foreground "blue"))))
 '(widget-documentation-face ((((class color) (background light)) (:foreground "green"))))
 '(widget-field-face ((((class grayscale color) (background light)) (:background "gray20"))))
 '(zmacs-region ((t (:foreground "white" :background "orchid4" :inverse-video nil))) t))
